version: "3.1"
services:
  app:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - egregiousdb:/mnt/egregiousdb
    restart: on-failure
volumes:
  egregiousdb:
    external: true
