version: "3.1"
services:
  proxy:
    build:
      context: ./dev-https-proxy
    links:
      - app
    ports:
      - "5001:443"
  app:
    volumes:
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
      - ./egregiousdb:/mnt/egregiousdb
