name: prod

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        env:
          DEPLOYMENT_SSH_KEY: ${{ secrets.DEPLOYMENT_SSH_KEY }}
        run: ./scripts/deploy.sh
